package io.daobab.generator.template;

public enum TemplateType {

    DATABASE_TABLES_INTERFACE,
    DATA_BASE_TARGET_CLASS,
    TABLE_CLASS,
    COLUMN_INTERFACE,
    COMPOSITE_KEY_TEMP,
    PK_COL_METHOD,
    COMPOSITE_PK_KEY_METHOD,
    COMPOSITE_METHOD,
}
