package io.daobab.statement.function.base;

public enum DatePeriod {

    YEAR, QUARTER, MONTH, WEEK, DAY, HOUR, MINUTE, SECOND, MILLISECOND,
    TIMEZONE_HOUR, TIMEZONE_MINUTE, TIMEZONE_SECOND, YEAR_MONTH,
    DAY_HOUR, DAY_MINUTE, DAY_SECOND, DAY_MICROSECOND,
    HOUR_MINUTE, HOUR_SECOND,
    MINUTE_SECOND, HOUR_MICROSECOND, MINUTE_MICROSECOND, SECOND_MICROSECOND


}
