package io.daobab.model;

/**
 * The strategy used to obtain a new primary key value on insert.
 *
 * @author Klaudiusz Wojtkowiak, (C) Elephant Software
 */
public enum IdGeneratorType {

    /**
     * A database sequence (requires {@link TableInformation#sequenceName()}).
     */
    SEQUENCE,
    /** An auto-increment / identity column generated by the database. */
    AUTO_INCREMENT,
    /** No generation - the id is supplied by the caller. */
    NONE,
    /** A Daobab-provided in-application generator. */
    GENERATOR
}
