package io.daobab.generator;

public interface GenKeys {

    String TARGET_CLASS_NAME = "__TARGET_CLASS_NAME";
    String TAB_ARRAY = "__TAB_ARRAY";
    String TARGET_TABLES_INTERFACE = "__TARGET_TABLES_INTERFACE";
    String TARGET_PACKAGE = "__TARGET_PACKAGE";
    String TABLES_INTERFACE_NAME = "__TABLES_INTERFACE_NAME";
    String TAB_IMPORTS = "__TAB_IMPORTS";
    String TABLES_INITIATED = "__TABLES_INITIATED";
    String TABLE_CAMEL_NAME = "__TABLE_CAMEL_NAME";
    String FIELDS = "__FIELDS";
    String CLASS_FULL_NAME = "__CLASS_FULL_NAME";
    String COLUMN_NAME = "__COLUMN_NAME";
    String TABLES_AND_TYPE = "__TABLES_AND_TYPE";
    //    String __COLUMN_NAME_REAL="__COLUMN_NAME_REAL";
    String INTERFACE_NAME = "__INTERFACE_NAME";
    String FIELD_NAME = "__FIELD_NAME";
    String DB_TYPE = "__DB_TYPE";
    String PACKAGE = "__PACKAGE";
    String CLASS_SIMPLE_NAME = "__CLASS_SIMPLE_NAME";
    String PK_IMPORT = "__PK_IMPORT";
    String PK_TYPE_IMPORT = "__PK_TYPE_IMPORT";
    String COLUMN_IMPORTS = "__COLUMN_IMPORTS";
    String COMPOSITE_KEY_COLUMN_TYPE_INTERFACES = "__COMPOSITE_KEY_COLUMN_TYPE_INTERFACES";
    String COMPOSITE_KEY_COLUMN_INTERFACES = "__COMPOSITE_KEY_COLUMN_INTERFACES";
    String COLUMN_INTERFACES = "__COLUMN_INTERFACES";
    String TABLE_NAME = "__TABLE_NAME";
    String COMPOSITE_NAME = "__COMPOSITE_NAME";
    String COLUMN_METHODS = "__COLUMN_METHODS";
    String PK_ID_METHOD = "__PK_ID_METHOD";
    String COMPOSITE_KEY_METHOD = "__COMPOSITE_KEY_METHOD";
    String PK_INTERFACE = "__PK_INTERFACE";
    String TABLE_PACKAGE = "__TABLE_PACKAGE";

}
